source 'http://rubygems.org'

gem 'middleman', '3.2.2'
gem 'middleman-blog'
gem 'middleman-gh-pages'
gem 'rake'
gem 'therubyracer'
gem 'bourbon'
gem 'middleman-neat'
gem 'rack-google-analytics'
gem 'middleman-livereload', '~> 3.1.0'